apiVersion: v1
kind: DeploymentConfig
metadata:
  name: dc-stress
spec:
  replicas: 1
  selector:
    name: stress
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        name: stress
    spec:
      containers:
      - image: alexbez/ocp-stress:v5
        imagePullPolicy: Always
        name: ocp-stress
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 200Mi
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
